// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSynchronizationActionInput - An input object to creating a SynchronizationAction
type CreateSynchronizationActionInput struct {
	DollarRef interface{} `json:"$ref,omitempty"`
	Ids       interface{} `json:"ids,omitempty"`
	Items     *int64      `json:"items,omitempty"`
}
