// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSettingInput - Object used for creating and updating SnowMirror Settings
type CreateSettingInput struct {
	Options *string `json:"options,omitempty"`
}
