// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSettingInput - A Settings object
type CreateSettingInput struct {
	Sync SyncronizationSyncOutput `json:"sync"`
}
