// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"snowmirror/internal/sdk/pkg/models/shared"
)

func (r *SettingResourceModel) ToCreateSDKType() *shared.CreateSettingInput {
	options := make(map[string]string)
	for optionsKey, optionsValue := range r.Options {
		optionsInst := optionsValue.ValueString()
		options[optionsKey] = optionsInst
	}
	var typeVar interface{}
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		_ = json.Unmarshal([]byte(r.Type.ValueString()), &typeVar)
	}
	out := shared.CreateSettingInput{
		Options: options,
		Type:    typeVar,
	}
	return &out
}

func (r *SettingResourceModel) ToUpdateSDKType() *shared.CreateSettingInput {
	out := r.ToCreateSDKType()
	return out
}
