// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"snowmirror/internal/sdk/pkg/models/shared"
)

func (r *SettingResourceModel) ToCreateSDKType() *shared.CreateSettingInput {
	options := new(string)
	if !r.Options.IsUnknown() && !r.Options.IsNull() {
		*options = r.Options.ValueString()
	} else {
		options = nil
	}
	out := shared.CreateSettingInput{
		Options: options,
	}
	return &out
}

func (r *SettingResourceModel) ToUpdateSDKType() *shared.CreateSettingInput {
	out := r.ToCreateSDKType()
	return out
}
