// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"snowmirror/internal/sdk/pkg/models/shared"
)

func (r *SettingResourceModel) ToCreateSDKType() *shared.CreateSettingInput {
	id := r.Sync.ID.ValueInt64()
	name := r.Sync.Name.ValueString()
	table := new(string)
	if !r.Sync.Table.IsUnknown() && !r.Sync.Table.IsNull() {
		*table = r.Sync.Table.ValueString()
	} else {
		table = nil
	}
	sync := shared.SyncronizationSyncOutput{
		ID:    id,
		Name:  name,
		Table: table,
	}
	out := shared.CreateSettingInput{
		Sync: sync,
	}
	return &out
}

func (r *SettingResourceModel) ToUpdateSDKType() *shared.CreateSettingInput {
	out := r.ToCreateSDKType()
	return out
}
