// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"snowmirror/internal/sdk/pkg/models/shared"
)

type CreateSynchronizationActionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Synchronization *shared.Synchronization
}
